name: Test Action

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - README.md

concurrency:
  group: test
  cancel-in-progress: false

jobs:
  test:
    strategy:
      matrix:
        formula:
          - test-formula-url
          - test-formula-git-revision
          - test-formula-pypi-url
        include:
          - formula: test-formula-url
            tap: dawidd6/test
            tag: v0.1.12
            force: true
          - formula: test-formula-git-revision
            tap: dawidd6/test
            tag: v0.3.3
            revision: c43abd765cf51c06bbcaa5479dc49aab1396989f
            force: true
          - formula: test-formula-pypi-url
            tap: dawidd6/test
            tag: v2.14.2
            force: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          tap: ${{matrix.tap}}
          formula: ${{matrix.formula}}
          tag: ${{matrix.tag}}
          revision: ${{matrix.revision}}
          force: ${{matrix.force}}
  test-livecheck-formula:
    runs-on: macos-latest
    needs:
      - test
    steps:
      - name: Wait
        run: sleep 30
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          message: test
          formula: |
            test-formula-url
            test-formula-git-revision
            test-formula-pypi-url
          tap: dawidd6/test
          force: true
          livecheck: true
  test-livecheck-tap:
    runs-on: ubuntu-latest
    needs:
      - test-livecheck-formula
    steps:
      - name: Wait
        run: sleep 30
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          message: |
            First line
            SECOND LINE
          tap: dawidd6/test
          force: true
          livecheck: true
